### ISSUE TITLE
Conflicting field types in your data

### ISSUE THREAD

**Issue by AlexMorrisonDev716** [robmarshall/gatsby-source-gravityforms#28]
Looks like there's an issue with the schema here. I have reason to believe this is causing issues with my gatsby cloud builds, but I thought I'd reach out first. Thanks!

```
If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them
with the `createTypes` action, and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
GF__Form.confirmations.pageId:
 - type: number
   value: 0
 - type: string
   value: ''
GF__Form.formFields.rangeMin:
 - type: boolean
   value: false
 - type: string
   value: ''
GF__Form.formFields.rangeMax:
 - type: boolean
   value: false
 - type: string
   value: ''
```
